Repository trailofbits/ebpf-common, pull requests merged in 2022-04, with the labels that each got.

#28 ci: Update the workflow file
  .github/workflows/main.yml
Labels: ci

#26 Permit to override which zlib library is linked
  CMakeLists.txt
  cmake/options.cmake
  libraries/LLVM/CMakeLists.txt
Labels: enhancement

#29 Fix build with system zlib
  libraries/LLVM/CMakeLists.txt
Labels: bug, cmake
